[ 2023-12-03 20:12:25,536 ] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.29.160:5000
[ 2023-12-03 20:12:25,536 ] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2023-12-03 20:12:41,812 ] 96 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 20:12:41] "GET /predict HTTP/1.1" 200 -
[ 2023-12-03 20:12:41,935 ] 96 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 20:12:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2023-12-03 20:12:54,298 ] 68 root - INFO - DataFrame Gathered
[ 2023-12-03 20:12:54,314 ] 69 root - INFO - Dataframe Head: 
     year  km_driven  mileage  engine  max_power  seats    fuel seller_type transmission        owner
0  2016.0    80000.0     22.0  1400.0       90.0    5.0  Diesel  Individual       Manual  First Owner
[ 2023-12-03 20:12:54,314 ] 46 root - INFO - Exception Occured in load_object function
[ 2023-12-03 20:12:54,314 ] 27 root - INFO - exception occured in prediction
[ 2023-12-03 20:12:54,314 ] 825 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "E:\ML\CarDekho_Car_Price_Prediction\src\utils.py", line 44, in load_object
    return pickle.load(file_obj, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: 'protocol' is an invalid keyword argument for load()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML\CarDekho_Car_Price_Prediction\src\pipeline\prediction_pipeline.py", line 18, in predict
    preprocessor=load_object(preprocessor_path)
  File "E:\ML\CarDekho_Car_Price_Prediction\src\utils.py", line 47, in load_object
    raise CustomException(e,sys)
src.exception.CustomException:  Error occured in python script name[E:\ML\CarDekho_Car_Price_Prediction\src\utils.py] line number [44] error message ['protocol' is an invalid keyword argument for load()]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML\CarDekho_Car_Price_Prediction\Carprice\lib\site-packages\flask-3.0.0-py3.10.egg\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ML\CarDekho_Car_Price_Prediction\Carprice\lib\site-packages\flask-3.0.0-py3.10.egg\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ML\CarDekho_Car_Price_Prediction\Carprice\lib\site-packages\flask-3.0.0-py3.10.egg\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ML\CarDekho_Car_Price_Prediction\Carprice\lib\site-packages\flask-3.0.0-py3.10.egg\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ML\CarDekho_Car_Price_Prediction\app.py", line 33, in predict_datapoint
    pred = predict_pipeline.predict(final_new_data)
  File "E:\ML\CarDekho_Car_Price_Prediction\src\pipeline\prediction_pipeline.py", line 28, in predict
    raise CustomException(e,sys)
src.exception.CustomException:  Error occured in python script name[E:\ML\CarDekho_Car_Price_Prediction\src\pipeline\prediction_pipeline.py] line number [18] error message [ Error occured in python script name[E:\ML\CarDekho_Car_Price_Prediction\src\utils.py] line number [44] error message ['protocol' is an invalid keyword argument for load()]]
[ 2023-12-03 20:12:54,322 ] 96 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 20:12:54] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
